export { default as Dashboard } from './Dashboard';
export { default as CreateCourse } from './CreateCourse';
export { default as CreateTutorial } from './CreateTutorial';
export { default as Topic } from './Topic';
export { default as TopicDetails } from './TopicDetails';
export { default as EnrolledCourses } from './EnrolledCourses';
export { default as StudentManagement } from './StudentManagement';
export { default as TrainerManagement } from './TrainerManagement';
export { default as CourseManagement } from './CourseManagement';