"use client";
import Head from "next/head";
import React, { Fragment, ReactNode } from "react";

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <Fragment>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex bg-gray-100 min-h-screen relative">
        <div className="flex-grow text-gray-800">
          {children}
        </div>
      </div>
    </Fragment>
  );
};

export default Layout;
