name: Deploy F2expert site to Pages
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "greeting"
      - name: Print goodbye
        run: echo "goodbye"
    
